"""
Unit and Integration Tests for Transition & Observation-Centric Scoring (SIH26060 - Person C).

Validates:
1. Mathematical correctness of last-step, recent-weighted, delta, and composite error functions.
2. Weight normalization and monotonicity of exponential weighting.
3. Shape compatibility for 2D and 3D input arrays.
4. Validation-only threshold selection and non-leakage.
5. Recovery-aware normal subset diagnostic calculations.
6. Schema integrity of generated transition scoring artifacts.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from ml.experiments.sensor_v2.calibrate_v2_sensors import search_threshold
from ml.experiments.sensor_v2.transition_score.scoring_functions import (
    compute_composite_transition_error,
    compute_delta_transition_error,
    compute_last_step_error,
    compute_recent_weighted_error,
    compute_recent_weights,
)

REPO_ROOT = Path(__file__).resolve().parent.parent.parent


class TestScoringFunctions:
    """Test pure scoring mathematical formulations."""

    def test_last_step_error_calculation(self) -> None:
        # 3D: (batch=2, seq_len=3, 1)
        x = np.array([[[1.0], [2.0], [3.0]], [[4.0], [5.0], [6.0]]])
        x_hat = np.array([[[1.0], [2.0], [1.0]], [[4.0], [5.0], [8.0]]])  # diffs at last: (3-1)=2, (6-8)=-2

        err = compute_last_step_error(x, x_hat)
        assert len(err) == 2
        assert np.isclose(err[0], 4.0)
        assert np.isclose(err[1], 4.0)

    def test_last_step_error_2d_shape(self) -> None:
        x = np.array([[1.0], [2.0], [5.0]])
        x_hat = np.array([[1.0], [2.0], [2.0]])
        err = compute_last_step_error(x, x_hat)
        assert isinstance(err, float)
        assert np.isclose(err, 9.0)

    def test_recent_weights_normalization_and_monotonicity(self) -> None:
        w = compute_recent_weights(seq_len=30, alpha=0.15)
        assert len(w) == 30
        assert np.isclose(np.sum(w), 1.0)
        # Weights should strictly increase with timestep
        assert np.all(np.diff(w) > 0)
        # Final timestep has highest weight
        assert w[-1] == np.max(w)

    def test_recent_weighted_error_calculation(self) -> None:
        x = np.zeros((1, 30, 1))
        x_hat = np.zeros((1, 30, 1))
        # Zero difference
        err_zero = compute_recent_weighted_error(x, x_hat)
        assert np.isclose(err_zero[0], 0.0)

        # Difference only at last timestep
        x[0, -1, 0] = 2.0
        w = compute_recent_weights(seq_len=30, alpha=0.15)
        err = compute_recent_weighted_error(x, x_hat, alpha=0.15)
        assert np.isclose(err[0], 4.0 * w[-1])

    def test_delta_transition_error_calculation(self) -> None:
        x = np.array([[[1.0], [2.0], [5.0]]])  # obs delta: 5 - 2 = 3
        x_hat = np.array([[[1.0], [2.0], [3.0]]])  # rec delta: 3 - 2 = 1
        err = compute_delta_transition_error(x, x_hat)
        # (3 - 1)^2 = 4
        assert np.isclose(err[0], 4.0)

    def test_composite_transition_error(self) -> None:
        x = np.array([[[1.0], [2.0], [5.0]]])  # last err: (5-3)^2 = 4, delta err: (3-1)^2 = 4
        x_hat = np.array([[[1.0], [2.0], [3.0]]])
        err = compute_composite_transition_error(x, x_hat, last_weight=0.5, delta_weight=0.5)
        assert np.isclose(err[0], 4.0)


class TestTransitionScoreEvaluationArtifacts:
    """Test JSON and Markdown artifacts generated by the transition scoring pipeline."""

    def test_transition_score_json_schema(self) -> None:
        json_path = (
            REPO_ROOT
            / "ml"
            / "experiments"
            / "sensor_v2"
            / "transition_score"
            / "results"
            / "transition_score_evaluation.json"
        )
        assert json_path.exists(), f"Missing transition scoring JSON artifact: {json_path}"

        with open(json_path, "r", encoding="utf-8") as f:
            doc = json.load(f)

        assert "stations" in doc
        assert "MTR" in doc["stations"]
        assert "BRT" in doc["stations"]

        for st_key in ["MTR", "BRT"]:
            st = doc["stations"][st_key]
            assert "formulations" in st
            assert "last_step_reconstruction" in st["formulations"]
            assert "recent_weighted_reconstruction" in st["formulations"]
            assert "delta_transition_error" in st["formulations"]
            assert "composite_transition_score" in st["formulations"]

            for m_key, m_info in st["formulations"].items():
                assert "operating_points" in m_info
                for crit in ["max_f1", "fpr_constrained", "balanced"]:
                    assert crit in m_info["operating_points"]
                    op = m_info["operating_points"][crit]
                    assert "test_metrics" in op
                    assert "normal_subset_analysis" in op
                    ns = op["normal_subset_analysis"]
                    assert "CLEAN_NORMAL" in ns
                    assert "CONTAMINATED_NORMAL" in ns

    def test_transition_score_markdown_exists(self) -> None:
        md_path = (
            REPO_ROOT
            / "ml"
            / "experiments"
            / "sensor_v2"
            / "transition_score"
            / "results"
            / "transition_score_comparison.md"
        )
        assert md_path.exists()
        assert md_path.stat().st_size > 500
